[tool.pyright]
    pythonVersion = '3.8'
    reportUnnecessaryTypeIgnoreComment = true

[tool.ruff]
    target-version = 'py38'
    line-length = 99

[tool.ruff.lint]
    select = ['E', 'F', 'B', 'Q', 'I', 'W', 'ASYNC', 'RUF']
    # E501:  line length over 79
    #        ignored in favor of ruff formatting
    ignore = ['E501']

[tool.ruff.lint.isort]
    combine-as-imports = true
    extra-standard-library = ['typing_extensions']
