[tool.pyright]
    pythonVersion = '3.8'
    reportUnnecessaryTypeIgnoreComment = true

[tool.ruff]
    target-version = 'py38'
    line-length = 99

[tool.ruff.lint]
    select = ['E', 'F', 'B', 'Q', 'I', 'W', 'ASYNC', 'RUF']
    ignore = [
        'RUF013',  # implicit-optional
                   # discord.py messes with how Optional is interpreted
        'E501',  # line-too-long
                 # not strictly incompatible with ruff-format but annoying nonetheless

        # ignore rules incompatible with ruff-format: https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
        'E501', 'W191', 'E111', 'E114', 'E117', 'D206', 'D300', 'Q000', 'Q001', 'Q002', 'Q003', 'COM812', 'COM819', 'ISC001', 'ISC002'
    ]

[tool.ruff.lint.isort]
    combine-as-imports = true
    extra-standard-library = ['typing_extensions']
