[tool.black]
    line-length = 99
    target-version = ['py38']
    include = '\.pyi?$'

[tool.pyright]
    pythonVersion = '3.8'
    reportUnnecessaryTypeIgnoreComment = true

[tool.ruff]
    target-version = 'py38'
    line-length = 99

[tool.ruff.lint]
    select = ['E', 'F', 'B', 'Q', 'I', 'W']
    ignore = ['E501']

[tool.ruff.lint.isort]
    combine-as-imports = true
    extra-standard-library = ['typing_extensions']
