[tool.black]
    line-length = 99
    target-version = ['py38']
    include = '\.pyi?$'

[tool.pyright]
    pythonVersion = '3.8'
    reportUnnecessaryTypeIgnoreComment = true

[tool.ruff]
    select = ['E', 'F', 'B', 'Q', 'I', 'W']
    ignore = ['E501']
    target-version = 'py38'
    line-length = 99

[tool.ruff.isort]
    combine_as_imports = true
    extra_standard_library = ['typing_extensions']
