name: style

on:
  push:
    branches:
      - master

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install prerequisite
        run: python -m pip install -U isort black
      - name: Run style
        run: |
          python -m isort --multi-line=3 --trailing-comma --force-grid-wrap=0 \
          --use-parentheses --line-width=99 `git ls-files "*.py"`
          python -m black -l 99 -t py38 `git ls-files "*.py"`
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: style with isort + black
          title: Style with isort + black
          body: |
            Automated style check
          labels: Automated, Style
          branch: automated/black
